# # version: "3.8"

# # services:
# #   frontend:
# #     build: ./Frontend
# #     ports:
# #       - "80:80"
# #     depends_on:
# #       - backend
# #     networks:
# #       - app-network

# #   backend:
# #     build: ./Backend
# #     ports:
# #       - "5000:8080"
# #       # - "5001:5001"
# #     environment:
# #       - ASPNETCORE_ENVIRONMENT=Development
# #     depends_on:
# #       - db
# #     networks:
# #       - app-network

# #   db:
# #     image: postgres:15
# #     restart: always
# #     environment:
# #       POSTGRES_DB: tmb
# #       POSTGRES_USER: tmbuser
# #       POSTGRES_PASSWORD: 123
# #     ports:
# #       - "5433:5432"
# #     volumes:
# #       - pgdata:/var/lib/postgresql/data
# #     networks:
# #       - app-network

# # volumes:
# #   pgdata:

# # networks:
# #   app-network:
# version: "3.8"

# services:
#   frontend:
#     build: ./Frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend
#     networks:
#       - app-network

#   backend:
#     build: ./Backend
#     ports:
#       - "5000:80"
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_URLS=http://+:80
#     depends_on:
#       - db
#     networks:
#       - app-network

#   db:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_DB: tmb
#       POSTGRES_USER: tmbuser
#       POSTGRES_PASSWORD: 123
#     ports:
#       - "5433:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - app-network

# volumes:
#   pgdata:

# networks:
#   app-network:
#     driver: bridge



version: "3.8"

services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./Backend
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - FrontendUrl=http://localhost:3000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tmb
      POSTGRES_USER: tmbuser
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge