services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./Backend
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - FrontendUrl=http://localhost:3000
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tmb;Username=tmbuser;Password=123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tmb
      POSTGRES_USER: tmbuser
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tmbuser -d tmb"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
